
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.39.33522 版
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.39.33522.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        E:/GitHub/smzy_study/cmake-build-debug/CMakeFiles/3.29.6/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:1216 (message)"
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        注意: 包含文件:  E:\\GitHub\\smzy_study\\cmake-build-debug\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "注意: 包含文件:  "
  -
    kind: "message-v1"
    backtrace:
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.39.33522 版
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.39.33522.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        E:/GitHub/smzy_study/cmake-build-debug/CMakeFiles/3.29.6/CompilerIdCXX/CMakeCXXCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:1216 (message)"
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        注意: 包含文件:  E:\\GitHub\\smzy_study\\cmake-build-debug\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "注意: 包含文件:  "
  -
    kind: "try_compile-v1"
    backtrace:
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:67 (try_compile)"
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "E:/GitHub/smzy_study/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-m9bjfq"
      binary: "E:/GitHub/smzy_study/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-m9bjfq"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/GitHub/smzy_study/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-m9bjfq'
        
        Run Build Command(s): "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/bin/cmake.exe" -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_49a3e\\fast
        	"C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_49a3e.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_49a3e.dir\\build
        Building C object CMakeFiles/cmTC_49a3e.dir/CMakeCCompilerABI.c.obj
        	"E:\\Program Files\\JetBrains\\CLion 2024.1.1\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_49a3e.dir\\CMakeCCompilerABI.c.obj.d --working-dir=E:\\GitHub\\smzy_study\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-m9bjfq --filter-prefix="注意: 包含文件:  " -- C:\\PROGRA~1\\MICROS~3\\2022\\PROFES~1\\VC\\Tools\\MSVC\\1439~1.335\\bin\\Hostx64\\x64\\cl.exe @C:\\Users\\20212\\AppData\\Local\\Temp\\nm2B91.tmp
        CMakeCCompilerABI.c
        Linking C executable cmTC_49a3e.exe
        	"E:\\Program Files\\JetBrains\\CLion 2024.1.1\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_49a3e.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe --manifests -- C:\\PROGRA~1\\MICROS~3\\2022\\PROFES~1\\VC\\Tools\\MSVC\\1439~1.335\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_49a3e.dir\\objects1.rsp @C:\\Users\\20212\\AppData\\Local\\Temp\\nm2BE0.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_49a3e.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_49a3e.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_49a3e.dir/manifest.res CMakeFiles\\cmTC_49a3e.dir/manifest.rc
        LINK Pass 1:
        C:\\PROGRA~1\\MICROS~3\\2022\\PROFES~1\\VC\\Tools\\MSVC\\1439~1.335\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_49a3e.dir\\objects1.rsp /out:cmTC_49a3e.exe /implib:cmTC_49a3e.lib /pdb:E:\\GitHub\\smzy_study\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-m9bjfq\\cmTC_49a3e.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_49a3e.dir/intermediate.manifest CMakeFiles\\cmTC_49a3e.dir/manifest.res
        MT:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_49a3e.dir/intermediate.manifest /out:CMakeFiles\\cmTC_49a3e.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_49a3e.dir/manifest.res CMakeFiles\\cmTC_49a3e.dir/manifest.rc
        FINAL LINK:
        C:\\PROGRA~1\\MICROS~3\\2022\\PROFES~1\\VC\\Tools\\MSVC\\1439~1.335\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_49a3e.dir\\objects1.rsp /out:cmTC_49a3e.exe /implib:cmTC_49a3e.lib /pdb:E:\\GitHub\\smzy_study\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-m9bjfq\\cmTC_49a3e.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_49a3e.dir/intermediate.manifest CMakeFiles\\cmTC_49a3e.dir/manifest.res
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:173 (message)"
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'C': C:/PROGRA~1/MICROS~3/2022/PROFES~1/VC/Tools/MSVC/1439~1.335/bin/Hostx64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:210 (cmake_determine_linker_id)"
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Running the C compiler's linker: "C:/PROGRA~1/MICROS~3/2022/PROFES~1/VC/Tools/MSVC/1439~1.335/bin/Hostx64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.39.33522.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
  -
    kind: "try_compile-v1"
    backtrace:
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:67 (try_compile)"
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "E:/GitHub/smzy_study/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-d15kb2"
      binary: "E:/GitHub/smzy_study/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-d15kb2"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/GitHub/smzy_study/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-d15kb2'
        
        Run Build Command(s): "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/bin/cmake.exe" -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_b8d9d\\fast
        	"C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_b8d9d.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_b8d9d.dir\\build
        Building CXX object CMakeFiles/cmTC_b8d9d.dir/CMakeCXXCompilerABI.cpp.obj
        	"E:\\Program Files\\JetBrains\\CLion 2024.1.1\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_b8d9d.dir\\CMakeCXXCompilerABI.cpp.obj.d --working-dir=E:\\GitHub\\smzy_study\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-d15kb2 --filter-prefix="注意: 包含文件:  " -- C:\\PROGRA~1\\MICROS~3\\2022\\PROFES~1\\VC\\Tools\\MSVC\\1439~1.335\\bin\\Hostx64\\x64\\cl.exe @C:\\Users\\20212\\AppData\\Local\\Temp\\nm2CF8.tmp
        CMakeCXXCompilerABI.cpp
        Linking CXX executable cmTC_b8d9d.exe
        	"E:\\Program Files\\JetBrains\\CLion 2024.1.1\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_b8d9d.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe --manifests -- C:\\PROGRA~1\\MICROS~3\\2022\\PROFES~1\\VC\\Tools\\MSVC\\1439~1.335\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_b8d9d.dir\\objects1.rsp @C:\\Users\\20212\\AppData\\Local\\Temp\\nm2D47.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_b8d9d.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_b8d9d.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_b8d9d.dir/manifest.res CMakeFiles\\cmTC_b8d9d.dir/manifest.rc
        LINK Pass 1:
        C:\\PROGRA~1\\MICROS~3\\2022\\PROFES~1\\VC\\Tools\\MSVC\\1439~1.335\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_b8d9d.dir\\objects1.rsp /out:cmTC_b8d9d.exe /implib:cmTC_b8d9d.lib /pdb:E:\\GitHub\\smzy_study\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-d15kb2\\cmTC_b8d9d.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_b8d9d.dir/intermediate.manifest CMakeFiles\\cmTC_b8d9d.dir/manifest.res
        MT:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_b8d9d.dir/intermediate.manifest /out:CMakeFiles\\cmTC_b8d9d.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_b8d9d.dir/manifest.res CMakeFiles\\cmTC_b8d9d.dir/manifest.rc
        FINAL LINK:
        C:\\PROGRA~1\\MICROS~3\\2022\\PROFES~1\\VC\\Tools\\MSVC\\1439~1.335\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_b8d9d.dir\\objects1.rsp /out:cmTC_b8d9d.exe /implib:cmTC_b8d9d.lib /pdb:E:\\GitHub\\smzy_study\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-d15kb2\\cmTC_b8d9d.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_b8d9d.dir/intermediate.manifest CMakeFiles\\cmTC_b8d9d.dir/manifest.res
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:173 (message)"
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'CXX': C:/PROGRA~1/MICROS~3/2022/PROFES~1/VC/Tools/MSVC/1439~1.335/bin/Hostx64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:210 (cmake_determine_linker_id)"
      - "E:/Program Files/JetBrains/CLion 2024.1.1/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Running the CXX compiler's linker: "C:/PROGRA~1/MICROS~3/2022/PROFES~1/VC/Tools/MSVC/1439~1.335/bin/Hostx64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.39.33522.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
